#### Font ####
font_size 13
font_family Fira Code Nerd Font Retina
# bold_font  mononoki Nerd Font Bold
# italic_font mononoki Nerd Font Italic
# bold_italic_font mononoki Nerd Font BoldItalic

#### Style ####
background_opacity 1
dynamic_background_opacity yes

window_padding_width 8.0

cursor_shape block

window_border_width 0.5
active_border_color #908698

hide_window_decorations no

tab_bar_style separator
tab_separator " | "

copy_on_select yes
strip_trailing_spaces always

url_style single
# open_url_modifiers ctrl

#### Perfomance ####
sync_to_monitor yes

#### Mappings ####
map cmd+c        copy_to_clipboard
map cmd+v        paste_from_clipboard
map shift+insert paste_from_clipboard

#### Remote controll ####
# listen_on unix:/tmp/mykitty
# allow_remote_control yes

#### Mac os settings ####
macos_option_as_alt yes
macos_titlebar_color background
macos_show_window_title_in all
macos_quit_when_last_window_closed no
macos_traditional_fullscreen yes

#### Startup ####
startup_session startup.conf

#### Shell Integration ####
shell_integration no-cursor

